modLoader="javafml" #mandatory
loaderVersion="[46,)"
license="All rights reserved"
[[mods]] #mandatory
modId="solidblocks" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Solid Blocks" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="Nicusha" #optional

description='''
Solid coloured blocks
'''
[[dependencies.solidblocks]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"
[[dependencies.solidblocks]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"